name: Trigger from Qase (DEMO)
on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: "Qase API URL"
        required: false
      qase_report:
        description: "Enabled/disabled reporting to Qase"
        required: false
      qase_project_code:
        description: "Qase project code"
        required: false
      qase_run_id:
        description: "Qase Run ID"
        required: false
      qase_run_complete:
        description: "Qase Run autocomplete"
        required: false

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url || vars.QASE_API_BASE_URL }}
  QASE_TESTOPS_PROJECT: ${{ inputs.qase_project_code || vars.QASE_TESTOPS_PROJECT }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_TESTOPS_RUN_COMPLETE: true
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_MODE: 'testops'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: cskmnrpt/qase-link-run@v2
        env:
          QASE_TESTOPS_API_TOKEN: ${{ env.QASE_TESTOPS_API_TOKEN }}
          QASE_TESTOPS_RUN_ID: ${{ env.QASE_RUN_ID }}
        continue-on-error: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Check QASE_RUN_ID and set environment variable
        id: check-run-id
        run: |
          # Ensure QASE_RUN_ID is not empty and is an integer
          if [[ -n "${{ env.QASE_RUN_ID }}" && "${{ env.QASE_RUN_ID }}" =~ ^[0-9]+$ ]]; then
            echo "QASE_TESTOPS_RUN_ID=${{ env.QASE_RUN_ID }}" >> $GITHUB_ENV
          else
            echo "QASE_RUN_ID is either empty or not an integer"
          fi

      - name: Run Playwright tests
        run: |
          npm test
